title: 문재웅의 작업실
description: 보안 관련 기술 조사 결과나 취미, 단상등을 기록하는 블로그입니다. 
author: Jaewoong Moon 
avatar: /moon.JPG
url: https://jaewoongmoon.github.io/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

skin: midnight

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Jaewoong Moon 
  card: summary
logo: logo.png
social:
  name: Jaewoong Moon
  links:
    - https://github.com/JaewoongMoon/
google_site_verification: 85b527edf4ba1c18
lang: ko
