title: 보안 취약점, 게임, 해킹 랩 
description: 주로 보안 취약점, 게임, 해킹 관련 기술을 연구하는 블로그입니다. 
author: Jaewoong Moon 
avatar: /moon.JPG

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

skin: midnight

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Jaewoong Moon 
  card: summary
logo: logo.png
social:
  name: Jaewoong Moon
  links:
    - https://github.com/JaewoongMoon/
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
